# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MGNetworking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MGNetworking
  pod 'AFNetworking', '~> 3.2.0'
  pod 'YTKKeyValueStore', '~> 0.1.2'
  pod 'MJExtension', '~> 3.0.13'
end
